version: '3.4'

services:
  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: govwifi_test
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10

  user_db:
    build: ./mysql_user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: govwifi_user_test
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10

  app:
    build: .
    environment:
      DB_NAME: govwifi_test
      DB_PASS: root
      DB_USER: root
      DB_HOSTNAME: db
      USER_DB_NAME: govwifi_user_test
      USER_DB_PASS: root
      USER_DB_USER: root
      USER_DB_HOSTNAME: user_db
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
      user_db:
        condition: service_healthy
