version: '3.4'

services:
  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: govwifi_test
    ports:
      - "13306:3306"

  app:
    build: .
    volumes:
      - ./:/usr/src/app
    environment:
      DB_NAME: govwifi_test
      DB_PASS: root
      DB_USER: root
      DB_HOSTNAME: db
    links:
      - db
    ports:
      - "8080:8080"
