# Provides database support for a locally hosted instance of the Logging API.
# The API app itself will be run by the developer outside of Docker; this offers
# a faster feedback loop when developing. Refer to the README for instructions.
services:
  user_and_session_db:
    image: mysql:8.0
    ports:
      - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_ROOT_HOST: "%"
