---
resources:
- name: govwifi-logging-api
  type: git
  source:
    uri: https://github.com/alphagov/govwifi-logging-api.git
    branch: concourse-spike

jobs:
  - name: lint
    plan:
      - get: govwifi-logging-api
      - task: lint
        file: ci/tasks/lint.yml
        privileged: true
  - name: test
    plan:
      - get: govwifi-logging-api
      - task: test
        file: ci/tasks/test.yml
        privileged: true
